// داده‌های اولیه، برگرفته از فایل اکسل ارائه‌شده.
window.SEED_CASES = [
 {
  "caseNo": "1404308",
  "expert": "نوروزی",
  "deliveryDate": "14050227",
  "status": "در انتظار وصول استعلام",
  "year": "1405",
  "intakeDate": "14040720",
  "reporterOrg": "سازمان بازرسی شهرداری تهران",
  "letterNo": "1404/11133/429/م",
  "letterDate": "14040715",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "محمد",
  "idNumber": "606",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "jobTitle": "کارشناس خدمات شهری 3",
  "jobGrade": "15",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 4",
  "servicePlace": "منطقه 4",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404337",
  "expert": "نوروزی",
  "deliveryDate": "14050227",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14040728",
  "reporterOrg": "سازمان بازرسی شهرداری تهران",
  "letterNo": "1404/11133/450/م",
  "letterDate": "14040723",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "پیره",
  "idNumber": "613",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "فوق لیسانس",
  "jobTitle": "کارشناس شهرسازی و معماری(3)",
  "jobGrade": "15",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 4",
  "servicePlace": "منطقه 4",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404380",
  "expert": "نوروزی",
  "status": "در انتظار وصول استعلام",
  "year": "1405",
  "intakeDate": "14040803",
  "reporterOrg": "سازمان بازرسی شهرداری تهران",
  "letterNo": "1404/11133/474/م",
  "letterDate": "14040730",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "محمد",
  "idNumber": "606",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "phone": "9194951462",
  "postTitle": "کارشناس خدمات شهری 3",
  "jobTitle": "کارشناس خدمات شهری 3",
  "jobGrade": "15",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 4",
  "servicePlace": "منطقه 4",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404381",
  "expert": "نوروزی",
  "status": "در انتظار وصول استعلام",
  "year": "1405",
  "intakeDate": "14040803",
  "reporterOrg": "سازمان بازرسی شهرداری تهران",
  "letterNo": "1404/11133/471/م",
  "letterDate": "14040730",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "محمد",
  "idNumber": "606",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "phone": "9194951462",
  "postTitle": "کارشناس خدمات شهری 3",
  "jobTitle": "کارشناس خدمات شهری 3",
  "jobGrade": "15",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 4",
  "servicePlace": "منطقه 4",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404388",
  "expert": "نوروزی",
  "deliveryDate": "14050227",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14040804",
  "reporterOrg": "سازمان بازرسی شهرداری تهران",
  "letterNo": "1404/11133/481م",
  "letterDate": "14040803",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "پیره",
  "idNumber": "613",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "فوق لیسانس",
  "phone": "9224275416",
  "postTitle": "کارشناس شهرسازی و معماری 3",
  "jobTitle": "کارشناس شهرسازی و معماری 3",
  "jobGrade": "15",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 4",
  "servicePlace": "منطقه 4",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404397",
  "expert": "نوروزی",
  "deliveryDate": "14050227",
  "status": "در انتظار وصول استعلام",
  "year": "1405",
  "intakeDate": "14040901",
  "reporterOrg": "سازمان بازرسی شهرداری تهران",
  "letterNo": "1404/11133/536م",
  "letterDate": "14040826",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "محمد",
  "idNumber": "606",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "phone": "9194951462",
  "postTitle": "کارشناس خدمات شهری 3",
  "jobTitle": "کارشناس خدمات شهری 3",
  "jobGrade": "منطقه 4",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 4",
  "servicePlace": "منطقه 4",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404512",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14041126",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/298/م",
  "letterDate": "14041120",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "ناصر",
  "idNumber": "19413",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "فوق دیپلم",
  "jobTitle": "اپراتور سامانه 137 (5)",
  "jobGrade": "13",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 14",
  "servicePlace": "منطقه 14",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404518",
  "expert": "نوروزی",
  "status": "ابلاغ و مختومه شد",
  "year": "1405",
  "intakeDate": "14041119",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/289/م",
  "letterDate": "14041112",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "احمد",
  "idNumber": "57",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "مجرد",
  "education": "زیر دیپلم",
  "jobTitle": "کارگر خدمات عمومی",
  "jobGrade": "0",
  "jobNature": "کارگری",
  "payrollPlace": "شرکت خاکریزآب",
  "orgUnit": "شرکت خاکریزآب",
  "servicePlace": "شرکت خاکریزآب",
  "servicePlaceType": "سازمان های مستقل",
  "contractType": "قرارداد مدت معین سازمان یا شرکت",
  "employmentStatus": "شاغل",
  "committeeDate": "14050504",
  "session": "11"
 },
 {
  "caseNo": "1404523",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14041129",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/13/م",
  "letterDate": "14041126",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "علی اکبر",
  "idNumber": "2940139059",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "jobTitle": "کارگر ساده",
  "jobGrade": "0",
  "jobNature": "کارگری",
  "payrollPlace": "شهرداری تهران",
  "orgUnit": "منطقه 2",
  "servicePlace": "منطقه 2",
  "servicePlaceType": "مناطق",
  "contractType": "کارگر رسمی",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404524",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14041129",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/12/م",
  "letterDate": "14041126",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "خسرو",
  "idNumber": "3720084078",
  "personnelCode": "1234567890",
  "gender": "زن",
  "maritalStatus": "متاهل",
  "education": "فوق لیسانس",
  "jobTitle": "دستیار 1",
  "jobGrade": "16",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "معاونت خدمات شهری و محیط زیست",
  "servicePlace": "معاونت خدمات شهری و محیط زیست",
  "servicePlaceType": "واحدهای ستادی",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404543",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14041206",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/م/314",
  "letterDate": "14041203",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "صفقلی",
  "idNumber": "645",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "معیل",
  "education": "لیسانس",
  "jobTitle": "کارشناس اداري 1",
  "jobGrade": "10",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت شهر سالم",
  "orgUnit": "معاونت درمان",
  "servicePlace": "مرکز بهداشتی و درمانی منطقه 3",
  "servicePlaceType": "شرکت های تابعه شهرداری تهران",
  "contractType": "قرارداد دائم سازمان یا شرکت",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404545",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14041206",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/م/316",
  "letterDate": "14041203",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "مسیب",
  "idNumber": "9988",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "فوق لیسانس",
  "jobTitle": "رئیس اداره حقوقی و تنظیم قرادادها",
  "jobGrade": "18",
  "jobNature": "کارمندی",
  "payrollPlace": "سازمان حمل و نقل و ترافیک",
  "orgUnit": "سازمان حمل و نقل و ترافیک",
  "servicePlace": "سازمان حمل و نقل و ترافیک",
  "servicePlaceType": "سازمان های غیر مستقل",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404546",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14041206",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/م/312",
  "letterDate": "14041203",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "محمدرضا",
  "idNumber": "1224",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "لیسانس",
  "jobTitle": "کارشناس متخصص مالی 1",
  "jobGrade": "12",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت شهر سالم",
  "orgUnit": "معاونت درمان",
  "servicePlace": "مرکز بهداشتی و درمانی منطقه 12",
  "servicePlaceType": "شرکت های تابعه شهرداری تهران",
  "contractType": "قرارداد مدت معین سازمان یا شرکت",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404547/1",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "رای صادر، ثبت و در انتظارابلاغ رای قرار گرفت",
  "year": "1405",
  "intakeDate": "14041206",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/م/317",
  "letterDate": "14041203",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "ارجعلی",
  "idNumber": "5440013318",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "فوق دیپلم",
  "jobTitle": "مامور شهربان 2",
  "jobGrade": "9",
  "jobNature": "کارگری",
  "payrollPlace": "موسسه هادیان شهر",
  "orgUnit": "منطقه 4",
  "servicePlace": "منطقه 4",
  "servicePlaceType": "مناطق",
  "contractType": "موسسه هادیان شهر",
  "employmentStatus": "شاغل",
  "committeeDate": "14050525",
  "session": "14"
 },
 {
  "caseNo": "1404547/2",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "رای صادر، ثبت و در انتظارابلاغ رای قرار گرفت",
  "year": "1405",
  "intakeDate": "14041206",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/م/317",
  "letterDate": "14041203",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "غلامعلی",
  "idNumber": "0016132386",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "jobTitle": "شهربان 2",
  "jobGrade": "2",
  "jobNature": "کارگری",
  "payrollPlace": "شهرداری تهران",
  "orgUnit": "منطقه 4",
  "servicePlace": "منطقه 4",
  "servicePlaceType": "مناطق",
  "contractType": "کارگر رسمی",
  "employmentStatus": "شاغل",
  "committeeDate": "14050525",
  "session": "14"
 },
 {
  "caseNo": "1404552/1",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14050122",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/321/م",
  "letterDate": "14041207",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "عباس",
  "idNumber": "506",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "لیسانس",
  "jobTitle": "کارشناس ارشد 1",
  "jobGrade": "16",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 15",
  "servicePlace": "منطقه 15",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404552/2",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14050122",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/321/م",
  "letterDate": "14041207",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "امیرقلی",
  "idNumber": "128",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "لیسانس",
  "jobTitle": "اپراتور سامانه 137 (6)",
  "jobGrade": "14",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 15",
  "servicePlace": "منطقه 15",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404552/3",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14050122",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/321/م",
  "letterDate": "14041207",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "اسداله",
  "idNumber": "20234",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "jobTitle": "نگهبان 7",
  "jobGrade": "9",
  "jobNature": "کارگری",
  "payrollPlace": "موسسه هادیان شهر",
  "orgUnit": "منطقه 15",
  "servicePlace": "منطقه 15",
  "servicePlaceType": "مناطق",
  "contractType": "موسسه هادیان شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1404555",
  "expert": "نوروزی",
  "deliveryDate": "14050222",
  "status": "رای صادر، ثبت و در انتظارابلاغ رای قرار گرفت",
  "year": "1405",
  "intakeDate": "14041029",
  "reporterOrg": "سازمان حراست شهرداری تهران",
  "letterNo": "112/1404/134/11/م",
  "letterDate": "14041020",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "خلیل",
  "idNumber": "50382",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "لیسانس",
  "jobTitle": "شهربان 1",
  "jobGrade": "3",
  "jobNature": "کارگری",
  "payrollPlace": "شهرداری تهران",
  "orgUnit": "منطقه 1",
  "servicePlace": "منطقه 1",
  "servicePlaceType": "مناطق",
  "contractType": "کارگر رسمی",
  "employmentStatus": "شاغل",
  "committeeDate": "14050525",
  "session": "14"
 },
 {
  "caseNo": "1405109",
  "expert": "نوروزی",
  "deliveryDate": "14050310",
  "status": "ابلاغ و مختومه شد",
  "year": "1405",
  "intakeDate": "14050303",
  "reporterOrg": "شرکت ساماندهی صنایع و مشاغل شهر",
  "letterNo": "620/206466",
  "letterDate": "14050302",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "داود",
  "idNumber": "7896",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "فوق لیسانس",
  "postTitle": "مدیر انتقال صنوف",
  "jobTitle": "مدیر ارشد 1",
  "jobNature": "کارمندی",
  "payrollPlace": "شهرداری تهران",
  "orgUnit": "شرکت ساماندهی صنایع و مشاغل شهر",
  "servicePlace": "شرکت ساماندهی صنایع و مشاغل شهر",
  "servicePlaceType": "شرکت های تابعه شهرداری تهران",
  "contractType": "قرارداد دائم سازمان یا شرکت",
  "employmentStatus": "شاغل",
  "committeeDate": "14050504",
  "session": "11"
 },
 {
  "caseNo": "1405111",
  "expert": "نوروزی",
  "deliveryDate": "14050303",
  "status": "ابلاغ و مختومه شد",
  "year": "1405",
  "intakeDate": "14050303",
  "reporterOrg": "سازمان بسيج شهرداري تهران",
  "letterNo": "210301 /705/581/زم",
  "letterDate": "14050303",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "مرتضی",
  "idNumber": "6363",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "فوق لیسانس",
  "jobTitle": "کارشناس آموزش(3)",
  "jobGrade": "15",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "سازمان بسیج شهرداری تهران",
  "servicePlace": "سازمان بسیج شهرداری تهران",
  "servicePlaceType": "سازمان های غیر مستقل",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل",
  "committeeDate": "14050331",
  "session": "8"
 },
 {
  "caseNo": "1405112",
  "expert": "نوروزی",
  "deliveryDate": "14050304",
  "status": "ابلاغ و مختومه شد",
  "year": "1405",
  "intakeDate": "14050304",
  "reporterOrg": "منطقه 18",
  "letterNo": "12/6371/518",
  "letterDate": "14050304",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "محمدعلی",
  "idNumber": "37817",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "زیر دیپلم",
  "postTitle": "کارگرساده",
  "jobTitle": "کارگرساده",
  "jobGrade": "5",
  "jobNature": "کارگری",
  "payrollPlace": "شهرداری تهران",
  "orgUnit": "منطقه 18",
  "servicePlace": "منطقه 18",
  "servicePlaceType": "مناطق",
  "contractType": "کارگر رسمی",
  "employmentStatus": "شاغل",
  "committeeDate": "14050504",
  "session": "11"
 },
 {
  "caseNo": "1405116",
  "expert": "نوروزی",
  "deliveryDate": "14050311",
  "status": "ابلاغ و مختومه شد",
  "year": "1405",
  "intakeDate": "14050311",
  "reporterOrg": "منطقه 5",
  "letterNo": "12024/505",
  "letterDate": "14050311",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "غلامحسین",
  "idNumber": "3510002581",
  "personnelCode": "1234567890",
  "gender": "زن",
  "maritalStatus": "مجرد",
  "education": "فوق لیسانس",
  "jobTitle": "کارشناس امور اجتماعی (2)",
  "jobGrade": "14",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 5",
  "servicePlace": "منطقه 5",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل",
  "committeeDate": "14050331",
  "session": "8"
 },
 {
  "caseNo": "1405118",
  "expert": "نوروزی",
  "deliveryDate": "14050313",
  "status": "ابلاغ و مختومه شد",
  "year": "1405",
  "intakeDate": "14050313",
  "reporterOrg": "سازمان پيشگيري و مديريت بحران شهرتهران",
  "letterNo": "190/161246",
  "letterDate": "14050222",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "سیفعلی",
  "idNumber": "0018164374",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "مجرد",
  "education": "دیپلم",
  "jobTitle": "نگهبان4",
  "jobGrade": "6",
  "jobNature": "کارگری",
  "payrollPlace": "موسسه هادیان شهر",
  "orgUnit": "سازمان پیشگیری و مدیریت بحران شهر تهران",
  "servicePlace": "سازمان پیشگیری و مدیریت بحران شهر تهران",
  "servicePlaceType": "سازمان های مستقل",
  "contractType": "موسسه هادیان شهر",
  "employmentStatus": "شاغل",
  "committeeDate": "14050324",
  "session": "7"
 },
 {
  "caseNo": "1405119",
  "expert": "نوروزی",
  "deliveryDate": "14050313",
  "status": "وفق مقررات اقدام و مختومه شد",
  "year": "1405",
  "intakeDate": "14050313",
  "reporterOrg": "منطقه22",
  "letterNo": "11624/522",
  "letterDate": "14050313",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "ابوالقاسم",
  "idNumber": "480",
  "personnelCode": "1234567890",
  "gender": "زن",
  "maritalStatus": "مجرد",
  "education": "دیپلم",
  "jobTitle": "کاردان 1",
  "jobGrade": "9",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه22",
  "servicePlace": "منطقه22",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل",
  "committeeDate": "14050504",
  "session": "11"
 },
 {
  "caseNo": "1405156",
  "expert": "نوروزی",
  "deliveryDate": "14050318",
  "status": "ابلاغ و مختومه شد",
  "year": "1405",
  "intakeDate": "14050318",
  "reporterOrg": "شرکت شهرسالم",
  "letterNo": "272197/ش",
  "letterDate": "14050317",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "عبداله",
  "idNumber": "161",
  "personnelCode": "1234567890",
  "gender": "زن",
  "maritalStatus": "متاهل",
  "education": "فوق لیسانس",
  "jobTitle": "کارشناس اداري 2",
  "jobGrade": "12",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت شهرسالم",
  "orgUnit": "شرکت شهرسالم",
  "servicePlace": "شرکت شهرسالم",
  "servicePlaceType": "سازمان های غیر مستقل",
  "contractType": "قرارداد مدت معین سازمان یا شرکت",
  "employmentStatus": "شاغل",
  "committeeDate": "14050421",
  "session": "9"
 },
 {
  "caseNo": "1405210",
  "expert": "نوروزی",
  "deliveryDate": "14050517",
  "status": "رای صادر، ثبت و در انتظارابلاغ رای قرار گرفت",
  "year": "1405",
  "intakeDate": "14050517",
  "reporterOrg": "منطقه 5",
  "letterNo": "28183/505",
  "letterDate": "14050517",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "علی اکبر",
  "idNumber": "8879",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "زیر دیپلم",
  "jobTitle": "کارگر فنی 3",
  "jobGrade": "10",
  "jobNature": "کارگری",
  "payrollPlace": "موسسه هادیان شهر",
  "orgUnit": "منطقه 5",
  "servicePlace": "منطقه 5",
  "servicePlaceType": "مناطق",
  "contractType": "موسسه هادیان شهر",
  "employmentStatus": "شاغل",
  "committeeDate": "14050601",
  "session": "15"
 },
 {
  "caseNo": "1405211",
  "expert": "نوروزی",
  "deliveryDate": "14050511",
  "status": "رای صادر، ثبت و در انتظارابلاغ رای قرار گرفت",
  "year": "1405",
  "intakeDate": "14050511",
  "reporterOrg": "منطقه 6",
  "letterNo": "21489/506",
  "letterDate": "14050511",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "مسعود",
  "idNumber": "6528",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "مجرد",
  "education": "دیپلم",
  "jobTitle": "مامورانتظامات ونگهبانی (2)",
  "jobGrade": "9",
  "jobNature": "کارگری",
  "payrollPlace": "موسسه هادیان شهر",
  "orgUnit": "منطقه 6",
  "servicePlace": "منطقه 6",
  "servicePlaceType": "مناطق",
  "contractType": "موسسه هادیان شهر",
  "employmentStatus": "شاغل",
  "committeeDate": "14050601",
  "session": "15"
 },
 {
  "caseNo": "1405219",
  "expert": "نوروزی",
  "deliveryDate": "14050510",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14050510",
  "reporterOrg": "منطقه 19",
  "letterNo": "16543/519",
  "letterDate": "14040510",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "محمد ابراهیم",
  "idNumber": "2715",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "jobTitle": "اپراتور سامانه 137 (6)",
  "jobGrade": "14",
  "jobNature": "کارمندی",
  "payrollPlace": "شرکت خدمات اداری شهر",
  "orgUnit": "منطقه 19",
  "servicePlace": "منطقه 19",
  "servicePlaceType": "مناطق",
  "contractType": "شرکت خدمات اداری شهر",
  "employmentStatus": "شاغل"
 },
 {
  "caseNo": "1405220",
  "expert": "نوروزی",
  "deliveryDate": "14050510",
  "status": "در دستور کار قرار گرفت",
  "year": "1405",
  "intakeDate": "14050510",
  "reporterOrg": "منطقه 19",
  "letterNo": "16544/519",
  "letterDate": "14050510",
  "caseType": "تنبیه",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "عبدالعلی",
  "idNumber": "4826",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "مجرد",
  "education": "لیسانس",
  "jobTitle": "مامور شهربان3",
  "jobGrade": "10",
  "jobNature": "کارگری",
  "payrollPlace": "موسسه هادیان شهر",
  "orgUnit": "منطقه 19",
  "servicePlace": "منطقه 19",
  "servicePlaceType": "مناطق",
  "contractType": "موسسه هادیان شهر",
  "employmentStatus": "شاغل",
  "committeeDate": "14050615",
  "session": "16"
 },
 {
  "caseNo": "1405232",
  "expert": "نوروزی",
  "deliveryDate": "14050517",
  "status": "مفتوح رسیدگی",
  "intakeDate": "14050517",
  "reporterOrg": "منطقه 14",
  "letterNo": "25439/514",
  "letterDate": "14050517",
  "caseType": "غیبت",
  "nationalId": "1234567890",
  "firstName": "غلامستان",
  "lastName": "اینده",
  "fatherName": "ابراهیم",
  "idNumber": "4355",
  "personnelCode": "1234567890",
  "gender": "مرد",
  "maritalStatus": "متاهل",
  "education": "دیپلم",
  "jobTitle": "بنا4",
  "jobGrade": "3",
  "jobNature": "کارگری",
  "payrollPlace": "شهرداری تهران",
  "orgUnit": "منطقه 14",
  "servicePlace": "منطقه 14",
  "servicePlaceType": "مناطق",
  "contractType": "کارگر رسمی",
  "employmentStatus": "شاغل"
 }
];
